/* eslint-disable */
/**
 * 作品集（PRD §13.1） —— 由 scripts/notion-sync.ts 從 Notion 產生，請勿手動編輯。
 * 要改內容請改 Notion，然後跑 `npm run sync:notion`。
 */
import type { Work } from './margin'

export const WORKS: Work[] = [
  {
    code: 'W-128',
    title: '霧感灰棕',
    service: 'color',
    stylist: 'yuki',
    length: '中長髮',
    note: '退到 9 度再上灰棕，透明感為主，不追求一次到位。',
    bleach: true,
    colorCode: '9/81 ＋ 護色',
    img: 'works_002',
  },
  {
    code: 'W-127',
    title: '霧灰亞麻',
    service: 'color',
    stylist: 'yuki',
    length: '長髮',
    note: '第二次補染，只調整根部三公分，髮尾不再上藥劑。',
    bleach: true,
    colorCode: '10/11 ＋ 護色',
    img: 'works_001',
  },
  {
    code: 'W-126',
    title: '淺棕漸層',
    service: 'color',
    stylist: 'yuki',
    length: '長髮',
    note: '從中段開始退，根部留原色，長出來時比較好接。',
    bleach: true,
    colorCode: '8/73 漸層',
    img: 'works_005',
  },
  {
    code: 'W-125',
    title: '深棕加深',
    service: 'color',
    stylist: 'yuki',
    length: '中長髮',
    note: '客人要能上班的顏色，室內看是深棕，陽光下才看得出紅。',
    bleach: false,
    colorCode: '5/56',
    img: 'works_003',
  },
  {
    code: 'W-124',
    title: '冷茶棕',
    service: 'color',
    stylist: 'yuki',
    length: '中長髮',
    note: '染後兩週回店做結構護髮，顏色掉得比較慢。',
    bleach: false,
    colorCode: '6/71',
    img: 'works_004',
  },
  {
    code: 'W-123',
    title: '灰藍打底',
    service: 'color',
    stylist: 'yuki',
    length: '短髮',
    note: '打底做兩次，中間隔一週，頭皮沒有不適才繼續。',
    bleach: true,
    colorCode: '9/8 ＋ 藍調 /88',
    img: 'works_006',
  },
  {
    code: 'W-122',
    title: '剪短一點',
    service: 'cut',
    stylist: 'ray',
    length: '短髮',
    note: '髮旋偏右，左側留長 1.5 公分平衡，吹整只要抓兩下。',
    bleach: false,
    img: 'works_011',
  },
  {
    code: 'W-121',
    title: '耳下三公分',
    service: 'cut',
    stylist: 'ray',
    length: '短髮',
    note: '髮量多，內層打薄兩層，外層保留重量線。',
    bleach: false,
    img: 'works_014',
  },
  {
    code: 'W-120',
    title: '層次長髮',
    service: 'cut',
    stylist: 'shu',
    length: '長髮',
    note: '長度一公分都不減，只重整層次與臉側線條。',
    bleach: false,
    img: 'works_015',
  },
  {
    code: 'W-119',
    title: '水波紋燙',
    service: 'perm',
    stylist: 'shu',
    length: '長髮',
    note: '髮況只撐得住中卷，捲度做小一號，三個月後再加強。',
    bleach: false,
    img: 'works_010',
  },
  {
    code: 'W-118',
    title: '空氣感微捲',
    service: 'perm',
    stylist: 'shu',
    length: '中長髮',
    note: '只燙外圈，內層不動，隔天洗完頭也還在。',
    bleach: false,
    img: 'works_007',
  },
  {
    code: 'W-117',
    title: '結構護髮',
    service: 'care',
    stylist: 'an',
    length: '長髮',
    note: '依受損程度調配，不做無效療程；這次只做中段到髮尾。',
    bleach: false,
    img: 'works_008',
  },
  {
    code: 'W-116',
    title: '頭皮調理',
    service: 'care',
    stylist: 'an',
    length: '中長髮',
    note: '夏天出油，先處理頭皮再談髮尾；一個月一次就夠。',
    bleach: false,
    img: 'works_017',
  },
  {
    code: 'W-115',
    title: '韓系燙髮',
    service: 'perm',
    stylist: 'shu',
    length: '中長髮',
    note: '捲度只做臉側兩段，其餘留直，長出來不會斷層。',
    bleach: false,
    img: 'works_009',
  },
]
